services:
  - type: web
    name: house-price-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    repo: https://github.com/Yuser00123/house-price-prediction-
